# Generated by Django 2.1.5 on 2019-01-25 03:02

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('pay_status', models.CharField(choices=[('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功'), ('NOTICE_FAIL', '通知失败')], default='PAYING', max_length=30, verbose_name='订单状态')),
                ('total_amount', models.FloatField(verbose_name='总金额')),
                ('order_no', models.CharField(max_length=100, unique=True, verbose_name='网站订单号')),
                ('user_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户留言')),
                ('pay_time', models.DateTimeField(blank=True, null=True, verbose_name='支付时间')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
                ('order_id', models.CharField(blank=True, max_length=100, null=True, verbose_name='商户订单号')),
                ('pay_url', models.TextField(blank=True, null=True, verbose_name='支付链接')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '订单管理',
                'verbose_name_plural': '订单管理',
            },
        ),
        migrations.CreateModel(
            name='WithDrawMoney',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('money', models.FloatField(verbose_name='提现金额')),
                ('real_money', models.FloatField(blank=True, null=True, verbose_name='实际到账金额')),
                ('bank_type', models.CharField(blank=True, max_length=15, null=True, verbose_name='银行类型')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='提现时间')),
                ('withdraw_status', models.CharField(choices=[('0', '处理中'), ('1', '已处理')], default='0', max_length=20, verbose_name='提现状态')),
                ('withdraw_no', models.CharField(blank=True, max_length=50, null=True, unique=True, verbose_name='提现单号')),
                ('user_msg', models.CharField(blank=True, max_length=200, null=True, verbose_name='用户留言')),
                ('receive_account', models.CharField(blank=True, max_length=50, null=True, verbose_name='账号')),
                ('receive_time', models.DateTimeField(blank=True, null=True, verbose_name='到账时间')),
                ('full_name', models.CharField(blank=True, max_length=20, null=True, verbose_name='姓名')),
                ('open_bank', models.CharField(blank=True, max_length=50, null=True, verbose_name='开户行')),
                ('receive_money_info', models.CharField(blank=True, max_length=200, null=True, verbose_name='收款信息')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='用户')),
            ],
            options={
                'verbose_name': '提现管理',
                'verbose_name_plural': '提现管理',
            },
        ),
    ]
