# Generated by Django 2.1.5 on 2019-01-25 08:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0002_auto_20190125_1533'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='pay_url',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('NOTICE_FAIL', '通知失败'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
