# Generated by Django 2.1.5 on 2019-01-25 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0004_auto_20190125_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='orderinfo',
            name='expire_time',
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('NOTICE_FAIL', '通知失败'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
