# Generated by Django 2.1.5 on 2019-01-25 09:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0005_auto_20190125_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('NOTICE_FAIL', '通知失败'), ('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='total_amount',
            field=models.DecimalField(decimal_places=2, max_digits=7, verbose_name='总金额'),
        ),
    ]
