# Generated by Django 2.1.5 on 2019-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0006_auto_20190125_1750'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='account_num',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='银行卡号'),
        ),
        migrations.AddField(
            model_name='orderinfo',
            name='bank_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='银行电话'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('NOTICE_FAIL', '通知失败')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
