# Generated by Django 2.1.5 on 2019-01-31 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20190131_1835'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='pay_url',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='支付链接'),
        ),
    ]
