# Generated by Django 2.1.5 on 2019-03-06 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0011_auto_20190305_1600'),
    ]

    operations = [
        migrations.AddField(
            model_name='withdrawmoney',
            name='remark_info',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('NOTICE_FAIL', '通知失败'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='withdrawmoney',
            name='withdraw_status',
            field=models.CharField(choices=[('0', '处理中'), ('1', '已处理'), ('2', '提现驳回')], default='0', max_length=20, verbose_name='提现状态'),
        ),
    ]
