# Generated by Django 2.1.5 on 2019-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0013_auto_20190308_1429'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='receive_way',
            field=models.CharField(choices=[('0', '支付宝转卡')], default='0', max_length=20, verbose_name='支付通道'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('NOTICE_FAIL', '通知失败'), ('TRADE_SUCCESS', '支付成功'), ('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
    ]
