# Generated by Django 2.1.5 on 2019-03-27 14:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('trade', '0014_auto_20190320_1549'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderinfo',
            name='money',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=7, null=True, verbose_name='实际金额'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='pay_status',
            field=models.CharField(choices=[('NOTICE_FAIL', '通知失败'), ('TRADE_CLOSE', '支付关闭'), ('PAYING', '待支付'), ('TRADE_SUCCESS', '支付成功')], default='PAYING', max_length=30, verbose_name='订单状态'),
        ),
        migrations.AlterField(
            model_name='orderinfo',
            name='receive_way',
            field=models.CharField(choices=[('0', 'atb')], default='0', max_length=20, verbose_name='支付通道'),
        ),
    ]
