# Generated by Django 2.1.5 on 2019-02-16 18:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='devicename',
            name='username',
            field=models.CharField(blank=True, max_length=25, null=True, unique=True, verbose_name='设备名称'),
        ),
    ]
