# Generated by Django 2.1.5 on 2019-01-24 09:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0003_bankinfo_user'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='bankinfo',
            options={'verbose_name': '收款管理', 'verbose_name_plural': '收款管理'},
        ),
        migrations.RenameField(
            model_name='userprofile',
            old_name='is_proxy',
            new_name='proxy',
        ),
    ]
