# Generated by Django 2.1.5 on 2019-02-27 16:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_noticeinfo'),
    ]

    operations = [
        migrations.CreateModel(
            name='VersionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('update_link', models.CharField(max_length=300, verbose_name='更新地址')),
                ('version_no', models.CharField(max_length=100, verbose_name='版本号')),
                ('remark', models.CharField(max_length=100, verbose_name='更新内容')),
                ('add_time', models.DateTimeField(default=datetime.datetime.now, verbose_name='创建时间')),
            ],
            options={
                'verbose_name': '版本管理',
                'verbose_name_plural': '版本管理',
            },
        ),
    ]
