# Generated by Django 2.1.5 on 2019-01-25 10:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_auto_20190125_1533'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='bank_tel',
            field=models.CharField(blank=True, max_length=15, null=True, verbose_name='银行电话'),
        ),
    ]
