# Generated by Django 2.1.5 on 2019-03-05 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0006_versioninfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='safe_code',
            field=models.CharField(default='123456', max_length=6, verbose_name='安全码'),
        ),
    ]
