# Generated by Django 2.1.5 on 2019-01-25 10:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0007_bankinfo_bank_tel'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=0, verbose_name='用户等级'),
        ),
    ]
