# Generated by Django 2.1.5 on 2019-01-30 14:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0008_userprofile_level'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='card_index',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='卡索引'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='login_token',
            field=models.CharField(blank=True, max_length=8, null=True, verbose_name='副token'),
        ),
    ]
