# Generated by Django 2.1.5 on 2019-01-31 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0009_auto_20190130_1436'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='level',
            field=models.IntegerField(default=3, verbose_name='用户等级'),
        ),
    ]
