# Generated by Django 2.1.5 on 2019-01-31 18:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0010_auto_20190131_1250'),
    ]

    operations = [
        migrations.AddField(
            model_name='bankinfo',
            name='bank_mark',
            field=models.CharField(blank=True, max_length=20, null=True, verbose_name='银行编号'),
        ),
    ]
