# Generated by Django 2.1.5 on 2019-03-20 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0011_operatelog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='operatelog',
            name='operate_type',
            field=models.CharField(choices=[('2', '提现管理'), ('3', '用户管理'), ('0', '登录管理'), ('1', '订单管理')], max_length=20, verbose_name='操作类型'),
        ),
    ]
