# Generated by Django 2.1.5 on 2019-02-15 15:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0012_devicename'),
    ]

    operations = [
        migrations.RenameField(
            model_name='devicename',
            old_name='name',
            new_name='username',
        ),
    ]
