# Generated by Django 2.1.5 on 2019-02-15 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0013_auto_20190215_1509'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bankinfo',
            name='account_num',
            field=models.CharField(max_length=35, unique=True, verbose_name='账号'),
        ),
    ]
